### ISSUE TITLE
Valid named attributes, char? not valid type

### ISSUE THREAD

**Issue by ClintDavis** [SoftCircuits/SoftCircuits.FixedWidthParser#1]
Char? is not a supported attribute type for named parameters. 
Compiler Error CS0655.

Works if I define an object like in the tests, but defeats the simplicity of being a class attribute.

**Comment by SoftCircuits** [comment]
It would be extremely helpful if you could post a snippet of code that shows exactly what line is causing the compile error.

**Comment by SoftCircuits** [comment]
This will be fixed in version 2.0.1.
